export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
  };
  
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode;
  }) {
    return (
            
         <>
          {children}
          <h3>Product Features</h3>
          </>
            
    );
  }
  